version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip_all
